// Define constants at the top of the file or in a separate constants file
export const MATINVENTORY_FILTER_OPTIONS = {

    brand: [
        { value: "", label: "All Brand" },
        { value: "jaquar", label: "Jaquar" }
    ],


    categories: [
        { value: "", label: "All Categories" },
        { value: "light", label: "Light" },
        { value: "socket", label: "Socket" },
        { value: "switches", label: "Switch" },
        { value: "regulator", label: "Regulators" },
    ],

    subcategories: [
        { value: "", label: "All Subcategories" },
        { value: "Downlights", label: "Downlights" },
        { value: "COB Downlights", label: "COB Downlights" },
        { value: "Designer Lights", label: "Designer Lights" },
        { value: "Panels", label: "Panels" },
        { value: "Battens-Tubes", label: "Battens-Tubes" },
        { value: "Magnetic Lights", label: "Magnetic Lights" },
        { value: "Retail Lights", label: "Retail Lights" },
        { value: "Industrial Lights", label: "Industrial Lights" }
    ],

    types: [
        { value: "", label: "All Types" },
        { value: "socket", label: "socket" },
        { value: "card-switch", label: "card-switch" },
        { value: "computer-socket", label: "computer-socket" },
        { value: "dimmer-switch", label: "dimmer-switch" },
        { value: "doorbell", label: "doorbell" },
        { value: "motion-sensor-switch", label: "motion-sensor-switch" },
        { value: "notify-switch", label: "notify-switch" },
        { value: "regulator", label: "regulator" },
        { value: "switch", label: "switch" },
        { value: "telephone-socket", label: "telephone-socket" },
        { value: "television-computer-socket", label: "television-computer-socket" },
        { value: "television-socket", label: "television-socket" },
        { value: "television-telephone-socket", label: "television-telephone-socket" },
    ],

    models: [
        { value: "", label: "All Models" },
        { value: "ENSAVE PLUS", label: "ENSAVE PLUS" },
        { value: "AREVA PRIME", label: "AREVA PRIME" },
        { value: "NERO SURFACE", label: "NERO SURFACE" },
        { value: "LUCENT", label: "LUCENT" },
        { value: "LUCENT SQUARE", label: "LUCENT SQUARE" },
        { value: "2 IN 1 STANDALONE", label: "2 IN 1 STANDALONE" },
        { value: "ERIS FIXED (LOW BORDER DEEP RECESSED)", label: "ERIS FIXED (LOW BORDER DEEP RECESSED)" },
        { value: "ESTUS SWIVEL", label: "ESTUS SWIVEL" },
        { value: "ERIS SWIVEL", label: "ERIS SWIVEL" },
        { value: "ERIS REFLECTO", label: "ERIS REFLECTO" },
        { value: "ERIS FIXED", label: "ERIS FIXED" },
        { value: "EMINA", label: "EMINA" },
        { value: "EMINA TILTABLE", label: "EMINA TILTABLE" },
        { value: "DIMAS", label: "DIMAS" },
        { value: "GLIDE", label: "GLIDE" },
        { value: "ERIS SURFACE ROUND", label: "ERIS SURFACE ROUND" },
        { value: "EPITO", label: "EPITO" },
        { value: "EMPHA", label: "EMPHA" },
        { value: "RENE", label: "RENE" },
        { value: "CYNO", label: "CYNO" },
        { value: "ULTIMA SLIM", label: "ULTIMA SLIM" },
        { value: "ACCESSORIES FOR ULTIMA SLIM", label: "ACCESSORIES FOR ULTIMA SLIM" },
        { value: "ULTIMA ULTRA SLIM 1x4", label: "ULTIMA ULTRA SLIM 1x4" },
        { value: "ULTIMA ULTRA SLIM 1x1", label: "ULTIMA ULTRA SLIM 1x1" },
        { value: "ULTIMA ULTRA PRO (2x2)", label: "ULTIMA ULTRA PRO (2x2)" },
        { value: "ULTIMA MULTI-COLOUR", label: "ULTIMA MULTI-COLOUR" },
        { value: "GLAZE", label: "GLAZE" },
        { value: "GLAZE ULTRA ALUMINIUM", label: "GLAZE ULTRA ALUMINIUM" },
        { value: "KUBIK SMART", label: "KUBIK SMART" },
        { value: "KUBIK ULTRA", label: "KUBIK ULTRA" },
        { value: "T8 RETRO", label: "T8 RETRO" },
        { value: "T8 RETRO ACCESSSORIES", label: "T8 RETRO ACCESSSORIES" },
        { value: "PRIDE", label: "PRIDE" },
        { value: "ORELLI SLIM", label: "ORELLI SLIM" },
        { value: "ORELLI SLIM HANGING", label: "ORELLI SLIM HANGING" },
        { value: "INSTARAY SLIM LINEAR WITH LENS", label: "INSTARAY SLIM LINEAR WITH LENS" },
        { value: "INSTARAY SLIM LINEAR", label: "INSTARAY SLIM LINEAR" },
        { value: "INSTARAY ROUND SLIM", label: "INSTARAY ROUND SLIM" },
        { value: "INSTARAY SLIM LINEAR DIFFUSED", label: "INSTARAY SLIM LINEAR DIFFUSED" },
        { value: "INSTARAY SLIM TILTABLE & DIFFUSED", label: "INSTARAY SLIM TILTABLE & DIFFUSED" },
        { value: "MAGNETIC TRACK LIGHT ACCESSORIES", label: "MAGNETIC TRACK LIGHT ACCESSORIES" },
        { value: "MULTIBLE ZOOM LIGHT", label: "MULTIBLE ZOOM LIGHT" },
        { value: "TRACK LIGHT WHITE", label: "TRACK LIGHT WHITE" },
        { value: "TRACK LIGHT BLACK", label: "TRACK LIGHT BLACK" },
        { value: "TRACK LIGHT ACCESSORIES", label: "TRACK LIGHT ACCESSORIES" },
        { value: "IP20 STRIP LIGHT (24V DC)", label: "IP20 STRIP LIGHT (24V DC)" },
        { value: "IP65 STRIP LIGHT (24V DC)", label: "IP65 STRIP LIGHT (24V DC)" },
        { value: "COB STRIP LIGHT", label: "COB STRIP LIGHT" },
        { value: "POWER SUPPLY FOR IP20 STRIP LIGHT", label: "POWER SUPPLY FOR IP20 STRIP LIGHT" },
        { value: "POWER SUPPLY FOR IP65 STRIP LIGHT", label: "POWER SUPPLY FOR IP65 STRIP LIGHT" },
        { value: "BULK HEAD", label: "BULK HEAD" },
        { value: "PIT LIGHT", label: "PIT LIGHT" },
        { value: "WELL GLASS", label: "WELL GLASS" },
        { value: "HIGHBAY (>100 Lm/W)", label: "HIGHBAY (>100 Lm/W)" },
        { value: "ULTRALITE HIGHBAY (>130 Lm/W)", label: "ULTRALITE HIGHBAY (>130 Lm/W)" }
    ]
};

// Then in your JSX, replace the hardcoded options with: